version: '3.8'

services:
  app:
    image: dimazyablicev/sirus:latest
    depends_on:
      - db
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgres://postgres:12345678@db:6666/sirus_production
      - SECRET_KEY_BASE=03ccedeaf832d7650c3ea3f00495be3093dac96970735e15c1aed9d18981b2862600ff19f23215f0bd120d49cd94bf4cea690f6c1e2e70b2c79228660b9edef2
    ports:
      - "3000:3000"
    volumes:
      - ./tmp:/app/tmp
      - ./logs:/app/log
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=sirus_production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6666:5432"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  postgres_data:
