default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: "localhost"
  port: 6666
  username: postgres
  password: 12345678
  database: sirus_development

test:
  <<: *default
  host: "localhost"
  port: 6666
  username: postgres
  password: 12345678
  database: sirus_test


production:
  primary: &primary_production
    <<: *default
    #  это локальный адрес postgresql но он считается внешним к контейнеру. Поэтому в postgresql настраиваем разрешение на подключение внешних запросов
    # host: 192.168.1.153
    host: db
    port: 6666
    database: sirus_production
    username: postgres
    password: 12345678

  cache:
    <<: *primary_production
    database: sirus_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: sirus_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: sirus_production_cable
    migrations_paths: db/cable_migrate

# Проверить статус	            sudo systemctl status postgresql@16-main
# Перезапустить кластер	        sudo systemctl restart postgresql@16-main
# Проверить соединения	        pg_isready
# Найти и редактировать конфиг	sudo nano /etc/postgresql/16/main/postgresql.conf
# Править доступ (pg_hba.conf)	sudo nano /etc/postgresql/16/main/pg_hba.conf
# nc -zv localhost 5432%