default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 6666) %>

development:
  <<: *default
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "12345678") %>
  database: <%= ENV.fetch("DB_NAME", "sirus_development") %>

test:
  <<: *default
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "12345678") %>
  database: <%= ENV.fetch("DB_NAME_TEST", "sirus_test") %>

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *primary_production
    database: sirus_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: sirus_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: sirus_production_cable
    migrations_paths: db/cable_migrate
